FROM elixir:latest

RUN apt-get update && apt-get install -y curl elixir fish git

RUN curl -sS https://starship.rs/install.sh | sh -s -- --yes

RUN useradd -ms /usr/bin/fish bdoliveira

USER bdoliveira

WORKDIR /home/bdoliveira

RUN yes Y | mix archive.install hex phx_new

RUN mkdir -p .config/fish/

RUN echo "add_newline = false" >> .config/starship.toml

RUN echo "set fish_greeting" >> .config/fish/config.fish

RUN echo "starship init fish | source" >> .config/fish/config.fish
